version: '3.9'

services:
  mysql_service:
    image: ${MYSQL_IMAGE_VERSION}
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      
      # 環境変数で指定した値を参照
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    restart: always
    command: --bind-address=0.0.0.0
    networks:
      - database_network

  mysql_cli:
    image: ${MYSQL_IMAGE_VERSION}
    networks:
      - database_network
    command: mysql -hmysql_service -u${MYSQL_USER} -p${MYSQL_PASSWORD} ${MYSQL_DATABASE}

networks:
  database_network:
    driver: bridge

